apiVersion: v1
description: Argonaut Resource Template - ART
home: https://argonaut.dev
maintainers:
  - email: dev@argonaut.dev
    name: Argonaut
name: stateless
version: v0.1.2
appVersion: v0.1.2
sources:
  - https://argonaut.dev
icon: https://argonaut.dev/images/logo-dark.png
