apiVersion: v1
name: istio-discovery
version: v0.3.3
tillerVersion: ">=2.7.2"
description: Helm chart for istio control plane
keywords:
  - istio
  - istiod
  - istio-discovery
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
