{{- $name := include "argonaut-deployment.uname" . -}}
{{- $releaseService := .Release.Service | quote -}}
{{- $releaseName := .Release.Name | quote -}}
{{- $chartName := .Chart.Name -}}

{{- range .Values.extraConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-{{ .name | lower }}"
  labels:
    heritage: {{ $releaseService }}
    release: {{ $releaseName }}
    chart: "{{ $chartName }}"
    app: {{ $name }}
data:
{{ toYaml .data | indent 2 }}
{{- end }}
