{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $env := .Values.argonaut.env -}}
{{- $cluster := .Values.argonaut.cluster -}}
{{- $version := .Values.version | default .Release.Revision -}}

{{- range .Values.extraConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-{{ .name | lower }}"
  labels:
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
    release: {{ $releaseName | quote }}
    env: {{ $env | quote }}
cluster: {{ $cluster | quote }}
    version: {{ $version | quote }}
data:
{{ toYaml .data | indent 2 }}
{{- end }}
