{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}

{{- $releaseNamespace := .Release.Namespace -}}
{{- $env := .Values.argonaut.env -}}
{{- $cluster := .Values.argonaut.cluster -}}
{{- $version := .Values.version | default .Release.Revision -}}

---
# Configure Service Ingress
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-http-services"
data:
  {{- range .Values.services }}
  {{- if or (eq .protocol "http") (eq .protocol "tls-terminated") (eq .protocol "https") (eq .protocol "grpc") (eq .protocol "grpcs") }}
  {{ .external.hostPort | default 443 }}: "{{ $releaseNamespace }}/{{ $name }}: {{- .port }}"
  {{- end }}
  {{- end }}
---
# Configure Service Ingress
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-tcp-services"
data:
  {{- range .Values.services }}
  {{- if (eq .protocol "tcp") }}
  {{ .external.hostPort | default 443 }}: "{{ $releaseNamespace }}/{{ $name }}: {{- .port }}"
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-udp-services"
data:
  {{- range .Values.services }}
  {{- if (eq .protocol "udp") }}
  {{ .external.hostPort | default 443 }}: "{{ $releaseNamespace }}/{{ $name }}: {{- .port }}"
  {{- end }}
  {{- end }}
---
{{- range .Values.services }}
{{ if and (ne .protocol "tcp") (ne .protocol "udp") (.external) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $name }}-{{- .port -}}-{{- .external.hostPort | default 443 -}}-ingress"
  labels:
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
    release: {{ $releaseName | quote }}
    env: {{ $env | quote }}
    cluster: {{ $cluster | quote }}
    version: {{ $version | quote }}
  annotations:
    {{- if .external.overrideAnnotations }}
    {{ toYaml .external.overrideAnnotations | nindent 4 }}
    {{- else }}
    {{- if .external.extraAnnotations }}
    {{ toYaml .external.extraAnnotations | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.class: nginx
    {{- if or (eq .protocol "tls-terminated") (eq .protocol "https") (eq .protocol "grpcs") }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- end }}
    {{- if eq .protocol "ssl-passthrough" }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    {{- end }}
    {{- end }}
spec:
  {{- $servicePort := .port }}
  {{- $external := .external }}
  {{- if or (eq .protocol "http") (eq .protocol "grpc") (eq .protocol "ssl-passthrough") }}
  rules:
    {{- range $external.hosts }}
    - host: {{ . | quote}}
      http:
        paths:
        {{- range $external.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name | quote }}
                port:
                  number: {{ $servicePort }}
        {{- end }}
    {{- end }}
  {{ else if or (eq .protocol "tls-terminated") (eq .protocol "grpcs") (eq .protocol "https") }}
  tls:
    - hosts:
      {{- range $external.hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: "{{ $name }}-{{- .port -}}-{{- .external.hostPort | default 443 -}}-ingress-tls-cert"
  rules:
    {{- range $external.hosts }}
    - host: {{ . | quote}}
      http:
        paths:
        {{- range $external.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name | quote }}
                port:
                  number: {{ $servicePort }}
        {{- end }}
    {{- end }}
  {{ end }}
---    
{{- end }}
{{- end }}
