{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $env := .Values.argonaut.env -}}
{{- $version := .Values.version | default .Release.Revision -}}

{{- if .Values.scaledObjectAuth -}}
{{ toYaml .Values.scaledObjectAuth }}
{{- end }}
---
{{- if .Values.scaledObject -}}
{{ toYaml .Values.scaledObject }}
{{- end }}
