{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $version := .Values.version | default .Release.Revision -}}

{{- if .Values.services -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-art-lb-cm"
  labels:
    heritage: {{ $releaseService | quote }}
    release: {{ $releaseName | quote }}
    chart: {{ $chartName | quote }}
    version: {{ $version | quote }}
    app: {{ $name | quote }}
data:
  loadbalancerYaml: |
    spec:
      ports:
        {{- range .Values.services }} 
        - name: "{{ .protocol | trunc 8 -}}-{{- randAlphaNum 6 | lower -}}"
          protocol: TCP
          port: {{ .ingress.port }}
        {{- end }}
  loadbalancerJson: |
    [
      {{- range .Values.services }}
      {    
        "op": "add",
        "path": "/spec/ports/-",
        "value":{
          "name": "{{ .protocol | trunc 8 -}}-{{- randAlphaNum 6 | lower -}}",
          "protocol": "TCP",
          "port": {{ .ingress.port }}
        }
      }
      {{- end }}
    ]
---
{{- end -}}