{{- $name := include "argonaut-deployment.sa" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $env := .Values.argonaut.env -}}
{{- $cluster := .Values.argonaut.cluster -}}
{{- $version := .Values.version | default .Release.Revision -}}

{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name | quote }}
  annotations:
    {{- with .Values.rbac.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
    release: {{ $releaseName | quote }}
    env: {{ $env | quote }}
    cluster: {{ $cluster | quote }}
    version: {{ $version | quote }}
{{- end -}}
