apiVersion: v1
description: Argonaut Resource Template - ART
home: https://argonaut.dev
maintainers:
  - email: dev@argonaut.dev
    name: Argonaut
name: stateful
version: v0.6.1
appVersion: v0.6.1
sources:
  - https://argonaut.dev
icon: https://argonaut.dev/images/logo-dark.png
