apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meilisearch.fullname" . }}-environment
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value | quote}}
  {{- end }}
