---
version: "v1"
appName: "nginx"
env: "dev"

host: "aws.tritonhq.io"

image: "nginx"
imageTag: "latest"
imageDigest: ""
imagePullPolicy: "IfNotPresent" # If imageTag = "latest", set this to "Always"

replicas: 1
resources:
  requests:
    cpu: "100m"
    memory: "200M"
  # limits:
  #   cpu: "200m"
  #   memory: "256M"

persistentStorage: []

entrypoint: ["echo"]
cmd: ["Hello World"]

services: []

# Can only do one of the httpGet and exec handler methods for livenessProbe
livenessProbe:
  # httpGet:
  #   path: /
  #   port: http
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env sh
        test -f /etc/
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

# Can only do one of the httpGet and exec handler methods for readinessProbe
readinessProbe:
  # # Handler 1
  # httpGet:
  #   path: /
  #   port: 80
  # Handler 2
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env sh
        test -f /etc/
  # Common fields
  failureThreshold: 5
  initialDelaySeconds: 10
  successThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 5
########################################################################################
