
{{- $name := include "argonaut-deployment.uname" . -}}
{{- $releaseService := .Release.Service | quote -}}
{{- $releaseName := .Release.Name | quote -}}
{{- $chartName := .Chart.Name -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "argonaut-deployment.uname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "argonaut-deployment.uname" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    version: {{ .Values.version | default .Release.Revision | quote }}
  annotations:
    {}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: "{{ template "argonaut-deployment.uname" . }}"
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      name: "{{ template "argonaut-deployment.uname" . }}"
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}"
        app: "{{ template "argonaut-deployment.uname" . }}"
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{/* This forces a restart if the configmap has changed */}}
        {{- if .Values.extraConfig }}
        configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
{{- end }}
{{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | quote | indent 8 }}
{{- end }}
      {{- if .Values.rbac.create }}
      serviceAccount: "{{ template "argonaut-deployment.uname" . }}"
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases: {{ toYaml .Values.hostAliases | quote | nindent 6 }}
      {{- end }}
      volumes:
        {{- if .Values.persistentStorage }}
        {{- range $index, $volumeMount := .Values.persistentStorage }}
        - name: "storage-vol-{{ $index }}"
          emptyDir: {}
        {{- end }}
        {{- end }}
        {{- range .Values.secretMounts }}
        # Mount Secrets
        - name: {{ .name | quote }}
          secret:
            secretName: {{ .secretName | quote  }}
            {{- if .defaultMode }}
            defaultMode: {{ .defaultMode | quote  }}
            {{- end }}
        {{- end }}
        {{- if .Values.extraConfig }}
        # extraConfig
        - name: extraconfig
          configMap:
            name: {{ template "argonaut-deployment.uname" . }}-extraconfig
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if or (eq .Values.antiAffinity "hard") (eq .Values.antiAffinity "soft") .Values.nodeAffinity | quote }}
      affinity:
        {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "{{ template "argonaut-deployment.uname" .}}"
            topologyKey: {{ .Values.antiAffinityTopologyKey }}
        {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: {{ .Values.antiAffinityTopologyKey }}
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "{{ template "argonaut-deployment.uname" . }}"
        {{- end }}
      {{- end }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: argonaut.dev/environment-{{ .Values.env }}
                operator: In
                values:
                  - "true"
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ template "argonaut-deployment.uname" . }}-img-secret
      {{- end }}
      {{- if .Values.initContainer.enabled }}
      initContainers:
      - name: init-container
        securityContext:
          # runAsUser: 0
          # privileged: true
        image: "{{ .Values.initContainer.image }}"
        {{- if eq .Values.initContainer.image "latest" }}
        imagePullPolicy: "Always"
        {{- else }}
        imagePullPolicy: "IfNotPresent"
        {{- end }}
        command: {{ .Values.initContainer.command }}
        {{- if .Values.initResources }}
        resources:
{{ toYaml .Values.initResources | indent 10 }}
        {{- end }}
        {{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
        {{- end }}
      {{- end }}
      containers:
      - name: "{{ template "argonaut-deployment.name" . }}"
        {{- if .Values.securityContext }}
        securityContext:
{{ toYaml .Values.securityContext | indent 10 }}
        {{- end }}
        image: "{{ template "argonaut-deployment.imageName" . }}"
        {{- if eq .Values.imageTag "latest" }}
        imagePullPolicy: "Always"
        {{- else }}
        imagePullPolicy: "IfNotPresent"
        {{- end }}
        ports:
        {{- range .Values.services }}
        - name: "{{ .protocol | trunc 5 -}}-{{- $name | trunc 4 -}}-{{- randAlphaNum 4 | lower -}}"
        # - name: "{{ $name | trunc 4 -}}-{{- .name | trunc 9 }}"
          containerPort: {{ .port }}
          # protocol: {{ .protocol }}
        {{- end }}
        {{- if .Values.entrypoint }}
        command: {{ .Values.entrypoint }}
        {{- end }}
        {{- if .Values.cmd }}
        args: {{ .Values.cmd }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 10 }}
{{- end }}
{{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
{{- end }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        lifecycle:
{{ toYaml .Values.lifecycle | indent 10 }}
        {{- if .Values.persistentStorage }}
        volumeMounts:
          {{- range $index, $volumeMount := .Values.persistentStorage }}
          - name: "storage-vol-{{ $index }}"
            mountPath: "{{ $volumeMount.mountPath }}"
          {{- end }}
        {{- end }}
          {{ if .Values.keystore }}
          - name: keystore
            mountPath: /usr/share/"{{ template "argonaut-deployment.uname" . }}"/config/"{{ template "argonaut-deployment.uname" . }}".keystore
            subPath: "{{ template "argonaut-deployment.uname" . }}".keystore
          {{ end }}
          {{- range .Values.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- range $path, $config := .Values.extraConfig }}
          - name: extraconfig
            mountPath: /usr/share/"{{ template "argonaut-deployment.uname" . }}"/config/{{ $path }}
            subPath: {{ $path }}
          {{- end -}}
          {{ if .Values.extraContainers }}
{{ toYaml .Values.extraContainers  | quote | indent 6 }}
          {{- end -}}

