
{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $env := .Values.argonaut.env -}}
{{- $cluster := .Values.argonaut.cluster -}}
{{- $version := .Values.version | default .Release.Revision -}}


{{- range $index, $value := .Values.externalServices }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: "{{- .name }}"
  labels:
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
    release: {{ $releaseName | quote }}
    env: {{ $env | quote }}
    cluster: {{ $cluster | quote }}
    version: {{ $version | quote }}
spec:
  hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  ports:
  {{- range .ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      number: {{ .number }}
  {{- end }}
  resolution: {{ .resolution }} # DNS
  location: {{ .location }}
---
{{- $svcName := .name -}}
{{- range .hosts }}
kind: Service
apiVersion: v1
metadata:
 name: {{ $svcName | quote }}
 labels:
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
    release: {{ $releaseName | quote }}
    env: {{ $env | quote }}
    cluster: {{ $cluster | quote }}
    version: {{ $version | quote }}
spec:
 type: ExternalName
 externalName: {{ . }}
---
{{- end }}
{{- end }}

