{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $env := .Values.argonaut.env -}}
{{- $version := .Values.version | default .Release.Revision -}}

---
# Configure Service Ingress
{{- range .Values.services }}
{{ if or (eq .protocol "http") (eq .protocol "tls-terminated")}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $name }}-{{- .port -}}-ingress"
  labels:
    helm.sh/chart: {{ $chartName | quote }}
    app.kubernetes.io/name: {{ $name | quote }}
    app.kubernetes.io/managed-by: {{ $releaseService | quote }}
    app.kubernetes.io/instance: {{ $releaseName | quote }}
    argonaut.dev/env: {{ $env | quote }}
    app.kubernetes.io/version: {{ $version | quote }}
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  {{- $servicePort := .port }}
  # ingressClassName: nginx
  {{- if eq .protocol "http" }}
  rules:
    - host: {{ .external.host | quote }}
      http:
        paths:
        {{- range .external.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name | quote }}
                port:
                  number: {{ $servicePort }}
        {{- end }}
  {{ else if eq .protocol "tls-terminated" }}
  {{- $external := .external }}
  tls:
    - hosts:
      {{- range $external.hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: "{{ $name }}-tls-cert"
  rules:
    {{- range $external.hosts }}
    - host: {{ . | quote}}
      http:
        paths:
        {{- range $external.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name | quote }}
                port:
                  number: {{ $servicePort }}
        {{- end }}
    {{- end }}
  {{ end }}
---
{{ end }}
{{- end }}
