{{- $name := include "argonaut-deployment.uname" . -}}
{{- $releaseNamespace := .Release.Namespace -}}

{{- if .Values.scaledObjectAuth -}}
{{ toYaml .Values.scaledObjectAuth }}
{{- end }}
---
{{- if .Values.scaledObject -}}
{{ toYaml .Values.scaledObject }}
{{- else }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "cpu-{{ $name }}-scaledobject"
  namespace: {{ $releaseNamespace }}
spec:
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 1
  scaleTargetRef:
    name: {{ $name }}
    kind: Deployment
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
{{- end }}
