{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $version := .Values.version | default .Release.Revision -}}
{{- $hosts := .Values.hosts -}}
{{- $rand := randAlphaNum 6 | lower -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-art-gw-cm"
  labels:
    heritage: {{ $releaseService | quote }}
    release: {{ $releaseName | quote }}
    chart: {{ $chartName | quote }}
    version: {{ $version | quote }}
    app: {{ $name | quote }}
data:
  gatewayYaml: |
    spec:
      servers:
      {{- range .Values.services }} 
        - port:
            number: {{ .ingress.port }}
            name: "{{ .protocol | trunc 8 -}}-{{- $rand -}}"
            {{- if or (eq .protocol "https") (eq .protocol "tls") }}
            protocol: "https"
            {{- else }}
            protocol: {{ .protocol | quote }}
            {{- end}}
            protocol: {{ .protocol }}
          hosts:
            {{- range $hosts }}
            - {{ . | quote }}
            {{- end }}
          {{- if or (eq .protocol "https") (eq .protocol "tls") }}
          {{- if eq .ingress.tls "terminated" }}
          tls:
            mode: SIMPLE
            credentialName: ingress-letsencrypt # must be the same as secret
          {{- else if eq .ingress.tls "passthrough" }}
          tls:
            mode: PASSTHROUGH
            credentialName: ingress-letsencrypt # must be the same as secret
          {{- end }}
          {{- end }}
      {{- end }}
  gatewayJson: |
    [
      {{- range .Values.services }} 
      {{- if and (.ingress) (.ingress.enabled)}}
      {
        "op": "add",
        "path": "/spec/servers/-",
        "value":{
          "port":{
              "number": {{ .ingress.port }},
              "name": "{{ .protocol | trunc 8 -}}-{{- $rand -}}",
              {{- if or (eq .protocol "https") (eq .protocol "tls") }}
              "protocol": "https"
              {{- else }}
              "protocol": {{ .protocol | quote }}
              {{- end}}
          },
          "hosts": [ {{- range $hosts -}} {{- . | quote -}}, {{- end -}} ],
          {{- if or (eq .protocol "https") (eq .protocol "tls") }}
          {{- if eq .ingress.tls "terminated" }}
          "tls": {
            "mode": "SIMPLE",
            "credentialName": "ingress-letsencrypt"
          },
          {{- else if eq .ingress.tls "passthrough" }}
          "tls": {
            "mode": "PASSTHROUGH",
            "credentialName": "ingress-letsencrypt",
          },
          {{- end }}
          {{- end }}
        }
      },
      {{- end }}
      {{- end }}
    ]

---