{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $env := .Values.argonaut.env -}}
{{- $version := .Values.version | default .Release.Revision -}}
{{- $ports := dict -}}

{{- if .Values.services -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name | quote }}
  labels:
    helm.sh/chart: {{ $chartName | quote }}
    app.kubernetes.io/name: {{ $name | quote }}
    app.kubernetes.io/managed-by: {{ $releaseService | quote }}
    app.kubernetes.io/instance: {{ $releaseName | quote }}
    argonaut.dev/env: {{ $env | quote }}
    app.kubernetes.io/version: {{ $version | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ $name | quote }}
    app.kubernetes.io/instance: {{ $releaseName | quote }}
    argonaut.dev/env: {{ $env | quote }}
    app.kubernetes.io/version: {{ $version | quote }}
  ports:
    {{- range $index, $service := .Values.services -}}
    {{- $p := $service.port | toString }}
    {{- if not ( hasKey $ports $p ) -}}
    {{- $_ := set $ports $p $p }}
    - name: "{{- if $service.name }} {{- $service.name -}} {{ else }} {{- $name | trunc 4 | trimSuffix "-" -}}-{{- $service.port -}}-{{- $index -}} {{ end -}}"
      protocol: TCP # UDP and SCTP are the other options
      port: {{ $service.port }}
    {{- end }}
    {{- end }}
---
{{- end -}}

