{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $env := .Values.argonaut.env -}}
{{- $cluster := .Values.argonaut.cluster -}}
{{- $version := .Values.version | default .Release.Revision -}}
{{- $ports := dict -}}

{{- if .Values.services -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name | quote }}
  labels:
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
    release: {{ $releaseName | quote }}
    env: {{ $env | quote }}
    cluster: {{ $cluster | quote }}
    version: {{ $version | quote }}
spec:
  type: ClusterIP
  selector:
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
    release: {{ $releaseName | quote }}
    env: {{ $env | quote }}
    cluster: {{ $cluster | quote }}
    version: {{ $version | quote }}
  ports:
    {{- range .Values.services -}}
    {{- $p := .port | toString }}
    {{- if not ( hasKey $ports $p ) -}}
    {{- $_ := set $ports $p $p }}
    - name: "{{- if .name }} {{- .name -}} {{ else }} {{- $name | trunc 4 | trimSuffix "-" -}}-{{- .port -}}-{{- randAlphaNum 4 | lower -}} {{ end -}}"
      protocol: TCP # UDP and SCTP are the other options
      port: {{ .port }}
    {{- end }}
    {{- end }}
---
{{- end -}}

