{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $env := .Values.env -}}
{{- $version := .Values.version | default .Release.Revision -}}

{{- if .Values.services -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name | quote }}
  labels:
    helm.sh/chart: {{ $chartName | quote }}
    app.kubernetes.io/name: {{ $name | quote }}
    app.kubernetes.io/managed-by: {{ $releaseService | quote }}
    app.kubernetes.io/instance: {{ $releaseName | quote }}
    argonaut.dev/env: {{ $env | quote }}
    app.kubernetes.io/version: {{ $version | quote }}
spec:
  type: ClusterIP
  selector:
    release: {{ $releaseName | quote }}
    chart: {{ $chartName | quote }}
    app: {{ $name | quote }}
  ports:
    {{- range .Values.services }} 
    - name: "{{ .protocol | trunc 5 -}}-{{- $name | trunc 4 -}}-{{- randAlphaNum 4 | lower -}}"
      protocol: TCP # UDP and SCTP are the other options
      port: {{ .port }}
    {{- end }}
---
{{- end -}}

