{{- $name := include "argonaut-deployment.uname" . -}}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ $name }}"
spec:
  maxReplicas: {{ int .Values.maxReplicas  }}
  minReplicas: {{ int .Values.minReplicas  }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ $name }}"
  targetCPUUtilizationPercentage: 80
