# Default values for clickhouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

zookeeper:
  # Number of nodes in ZooKeeper cluster. Set to either 1 or 3 or 5.
  nodes: 1  
clickhouse:
  shardsCount: 1
  replicasCount: 1
  password: "weakpassthatneedstobereplaced!"
  storage: "50Gi"
# nameOverride: "ch1"
externalLoadbalancer:
  enabled: false
  httpPort:
    number: 8123
    enabled: true
  tcpPort: 
    number: 9000
    enabled: true
  hostnames:
    - "ch1.example.com"
    - "ch2.example.com"
    - "ch3.example.com"
  