# Default values for clickhouse.
# This is a YAML-formatted file.

name: "ch1"
zookeeper:
  # Number of nodes in ZooKeeper cluster. Set to either 1 or 3 or 5.
  nodes: 1  
clickhouse:
  shardsCount: 1
  replicasCount: 1
  password: "weakpassthatneedstobereplaced!"
  storage: "5Gi"
ingress:
  enabled: true
  hosts:
    - "ch1.example.com"
    - "ch2.example.com"
